export const StylesOptions = {
  position: [
    { value: "initial", label: "Initial" },
    { value: "absolute", label: "Absolute" },
    { value: "fixed", label: "Fixed" },
    { value: "relative", label: "Relative" },
    { value: "static", label: "Static" },
    { value: "sticky", label: "Sticky" },
    { value: "inherit", label: "Inherit" },
  ],
  size: [
    { value: "initial", label: "Initial" },
    { value: "input", label: "Custome" },
    { value: "100%", label: "Fill" },
    { value: "max-content", label: "Content" },
    { value: "auto", label: "Auto" },
  ],
  borderStyle: [
    { value: "initial", label: "initial" },
    { value: "none", label: "None" },
    { value: "solid", label: "Solid" },
    { value: "dashed", label: "Dashed" },
    { value: "dotted", label: "Dotted" },
    { value: "double", label: "Double" },
    { value: "groove", label: "Groove" },
    { value: "ridge", label: "Ridge" },
    { value: "inset", label: "Inset" },
    { value: "outset", label: "Outset" },
  ],
  display: [
    { value: "initial", label: "Initial" },
    { value: "block", label: "Block" },
    { value: "inline", label: "Inline" },
    { value: "flex", label: "Flex" },
    { value: "grid", label: "Grid" },
  ],
  flexDirection: [
    { value: "initial", label: "Initial" },
    { value: "row", label: "Row" },
    { value: "row-reverse", label: "Row Reverse" },
    { value: "column", label: "Column" },
    { value: "column-reverse", label: "Column Reverse" },
  ],
  flexWrap: [
    { value: "initial", label: "Initial" },
    { value: "nowrap", label: "No Wrap" },
    { value: "wrap", label: "Wrap" },
    { value: "wrap-reverse", label: "Wrap Reverse" },
  ],
  justifyContent: [
    { value: "initial", label: "Initial" },
    { value: "flex-start", label: "Flex Start" },
    { value: "flex-end", label: "Flex End" },
    { value: "center", label: "Center" },
    { value: "space-between", label: "Space Between" },
    { value: "space-around", label: "Space Around" },
    { value: "space-evenly", label: "Space Evenly" },
  ],
  alignItems: [
    { value: "initial", label: "Initial" },
    { value: "flex-start", label: "Flex Start" },
    { value: "flex-end", label: "Flex End" },
    { value: "center", label: "Center" },
    { value: "baseline", label: "Baseline" },
  ],
  fontFamily: [
    { value: "initial", label: "Initial" },
    { value: "Arial", label: "Arial" },
    { value: "Helvetica", label: "Helvetica" },
    { value: "Times New Roman", label: "Times New Roman" },
    { value: "Times", label: "Times" },
  ],
  fontWeight: [
    { value: "initial", label: "Initial" },
    { value: "100", label: "100" },
    { value: "200", label: "200" },
    { value: "300", label: "300" },
    { value: "400", label: "400" },
    { value: "500", label: "500" },
    { value: "600", label: "600" },
    { value: "700", label: "700" },
  ],
  fontStyle: [
    { value: "initial", label: "Initial" },
    { value: "normal", label: "Normal" },
    { value: "italic", label: "Italic" },
    { value: "oblique", label: "Oblique" },
  ],
  textDecoration: [
    { value: "initial", label: "Initial" },
    { value: "none", label: "None" },
    { value: "underline", label: "Underline" },
    { value: "overline", label: "Overline" },
    { value: "line-through", label: "Line Through" },
  ],
  textTransform: [
    { value: "initial", label: "Initial" },
    { value: "none", label: "None" },
    { value: "capitalize", label: "Capitalize" },
    { value: "uppercase", label: "Uppercase" },
    { value: "lowercase", label: "Lowercase" },
  ],
  textAlign: [
    { value: "initial", label: "Initial" },
    { value: "left", label: "Left" },
    { value: "center", label: "Center" },
    { value: "right", label: "Right" },
    { value: "justify", label: "Justify" },
  ],
  textOverflow: [
    { value: "initial", label: "Initial" },
    { value: "clip", label: "Clip" },
    { value: "ellipsis", label: "Ellipsis" },
  ],
  whiteSpace: [
    { value: "initial", label: "Initial" },
    { value: "normal", label: "Normal" },
    { value: "nowrap", label: "No Wrap" },
    { value: "pre", label: "Pre" },
    { value: "pre-line", label: "Pre Line" },
    { value: "pre-wrap", label: "Pre Wrap" },
  ],
  overflow: [
    { value: "initial", label: "Initial" },
    { value: "visible", label: "Visible" },
    { value: "hidden", label: "Hidden" },
    { value: "scroll", label: "Scroll" },
    { value: "auto", label: "Auto" },
  ],
  objectFit: [
    { value: "initial", label: "Initial" },
    { value: "fill", label: "Fill" },
    { value: "contain", label: "Contain" },
    { value: "cover", label: "Cover" },
    { value: "none", label: "None" },
    { value: "scale-down", label: "Scale Down" },
  ],
};

